name: facebook/rocksdb/pr-jobs
on: [push, pull_request]
permissions: {}
jobs:
  build-linux:
    runs-on:
      labels: testing
    container:
      image: zjay437/rocksdb:0.6
      options: --shm-size=16gb
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - run: make V=1 J=32 -j32 check
    - uses: "./.github/actions/post-steps"